version: '3.8'

services:
  ingesta-ms1:
    build: ./ingesta/ms1_ingest
    container_name: ingesta_ms1_container
    environment:
      - DB_HOST=172.17.0.1
      - DB_NAME=bd_ms1
      - S3_BUCKET_NAME=proyecto-bucket-g5
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  ingesta-ms2:
    build: ./ingesta/ms2_ingest
    container_name: ingesta_ms2_container
    environment:
      - DB_HOST=172.17.0.1
      - DB_NAME=bd_ms2
      - S3_BUCKET_NAME=proyecto-bucket-g5
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  ingesta-ms3:
    build: ./ingesta/ms3_ingest
    container_name: ingesta_ms3_container
    environment:
      - MONGO_URI=mongodb://root:password@172.17.0.1:27017/
      - S3_BUCKET_NAME=proyecto-bucket-g5
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
